modLoader="javafml"
loaderVersion="[46,48)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/anthxnymc/KryptonReforged/issues"

[[mods]]
modId="krypton"
version="${version}"
displayName="Krypton Reforged"
displayURL="https://www.curseforge.com/minecraft/mc-mods/krypton-reforged"
logoFile="logo.png"
credits="anthxnymc, tuxed"
authors="anthxnymc"
displayTest="MATCH_VERSION"
description="A (Neo)Forge mod that optimizes the Minecraft networking stack and entity tracker."

[modproperties.krypton]
catalogueImageIcon="catalogue_icon.png"

[mods."canary:options"]
"mixin.world.player_chunk_tick"=false

[mods."radium:options"]
"mixin.world.player_chunk_tick"=false

[[dependencies.krypton]]
modId="forge"
mandatory=true
versionRange="[46,48)"
ordering="NONE"
side="BOTH"

[[dependencies.krypton]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.20.2)"
ordering="NONE"
side="BOTH"